version: "3"

tasks:
  migrate-up:
    cmds:
      - goose up
    description: "Run goose migrations (up)"

  migrate-down:
    cmds:
      - goose down
    description: "Rollback goose migrations (down)"

  unit-test:
    cmds:
      - go test ./tests/unit... -v
    description: "Run unit tests"

  integration-test:
    cmds:
      - go test ./tests/integration... -v
    description: "Run integration tests"

  test:
    cmds:
      - go test ./tests/... -v
    description: "Run all tests"

  generate-swagger:
    cmds:
      - swag init -g cmd/main.go
    description: "Generate swagger spec"
