basePath: /api/v1
host: localhost:5000
info:
  contact: {}
  description: This is your API description.
  title: Your API Title
  version: "1.0"
paths:
  /ping:
    get:
      description: Returns pong
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Ping example
      tags:
      - example
swagger: "2.0"
